export const selectors = {
    LATITUDE_DEGREES: '.latitude-degrees',
    LONGITUDE_DEGREES: '.longitude-degrees',
    LATITUDE_MINUTES: '.latitude-minutes',
    LONGITUDE_MINUTES: '.longitude-minutes',
    TIME: '.time',
    DATE: '.date',
    LOCATION: '.location',
    TEMPERATURE: '.today-temperature',
    SUMMARY: '.summary-value',
    APPARENT_TEMPERATURE: '.apparent-temperature-value',
    WIND: '.wind-value',
    HUMIDITY_VALUE: '.humidity-value',
    TEMPERATURE_TOMORROW: '.forecast-temperature-tomorrow',
    TEMPERATURE_SECOND_DAY: '.forecast-temperature-second-day',
    TEMPERATURE_THIRD_DAY: '.forecast-temperature-third-day',
    TOMORROW: '.tomorrow',
    SECOND_DAY:'.second-day',
    THIRD_DAY:'.third-day',
    TODAY_WEATHER_ICON:'.weather-icon-today',
    TOMORROW_WEATHER_ICON:'.weather-icon-tomorrow',
    SECOND_DAY_WEATHER_ICON:'.weather-icon-second-day',
    THIRD_DAY_WEATHER_ICON:'.weather-icon-third-day',
    TEMPERATURE_BTN_CONTAINER: '.temperature',
    FAHRENHEIT_TEMPERATURE_BTN: '.fahrenheit-temperature',
    CELSIUS_TEMPERATURE_BTN: '.celsius-temperature',
    BODY: 'body',
    BUTTONS_CONTAINER: '.buttons-container',
    SEARCH_FORM: '.search-container',
    SEARCH_INPUT_FIELD: '.input-field',
    LANGUAGE_BTN: '.language-button',
    ERROR_MESSAGE:'.error-message',
    TEMPERATURE_BTN: '.temperature-button',
}; 