export const weatherIcons = {
    '01d': 'day.svg',
    '01n': 'night.svg',
    '02d': 'cloudy-day-1.svg',
    '02n': 'cloudy-night-1.svg',
    '03d': 'cloudy.svg',
    '03n': 'cloudy.svg',
    '04d': 'cloudy.svg',
    '04n': 'cloudy.svg',
    '09d': 'rainy-6.svg',
    '09n': 'rainy-6.svg',
    '10d': 'rainy-1.svg',
    '10n': 'rainy-4.svg',
    '11d': 'thunder.svg',
    '11n': 'thunder.svg',
    '13d': 'snowy-4.svg',
    '13n': 'snowy-4.svg',
    '50d': 'mist.svg',
    '50n': 'mist.svg',    
};